# Use of php here is for legacy reasons and to keep the repo simple.
# No php is used in serving the site.
runtime: php84
automatic_scaling:
  min_instances: 1
  max_instances: 5
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /Resume.pdf
    static_files: www/KellenDonohueResume.pdf
    upload: www/KellenDonohueResume.pdf
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
