runtime: php83
api_version: 1
max_instances: 10

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /homepage.css
  static_files: homepage.css
  upload: homepage\.css
  
- url: /images
  static_dir: images

- url: /Resume.pdf
  static_files: Resume.pdf
  upload: Resume\.pdf

- url: /patent.pdf
  static_files: patent.pdf
  upload: patent\.pdf
  
- url: /keybase.txt
  static_files: keybase.txt
  upload: keybase\.txt

- url: /code.html
  static_files: code.html
  upload: code\.html

- url: /robots.txt
  static_files: robots.txt
  upload: robots\.txt

- url: .*
  script: index.html
