runtime: php83
automatic_scaling:
  min_instances: 1
  max_instances: 5
handlers:
  - url: /
    static_files: www/index.html
    upload: www/index.html
  - url: /Resume.pdf
    static_files: www/KellenDonohueResume.pdf
    upload: www/KellenDonohueResume.pdf
  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
